### ISSUE TITLE
QSO configuration not working anymore

### ISSUE THREAD

**Issue by gbrueckl** [microsoft/semantic-link-labs#101]
it seems that with V0.7.0 the QSO configuration is not working anymore
in particular those lines: https://github.com/microsoft/semantic-link-labs/blob/main/src/sempy_labs/_query_scale_out.py#L232C11-L232C44

as `set_semantic_model_storage_format` is not returning anything (anymore?), the check for `ssm == 200` always fails and the QSO configuration is never applied

**Comment by m-kovalsky** [comment]
Thanks. Made a PR for this fix.
