### ISSUE TITLE
BUG run_model_bpa_bulk

### ISSUE THREAD

**Issue by matiirueda** [microsoft/semantic-link-labs#109]
**Describe the bug**

I was reviewing the results of running the loop across all workspaces, and for most of the datasets, it couldn't save data. It returns this error: "Model BPA failed for the 'Linaje' semantic model within the 'CIO' workspace. Single positional indexer is out-of-bounds."
Most of the datasets from the workspaces are giving me that error. Do we know what might be causing it?
Do you know what might be causing this? I'll mention it on Git.

This is my code for example for the workspace "CIO"

import sempy_labs as labs
from pyspark.sql import SparkSession
from sempy_labs import migration,report,directlake
from sempy_labs import lakehouse as lake
from sempy_labs.tom import connect_semantic_model

labs.run_model_bpa_bulk(extended= True, language = 'es-ES' , workspace='CIO' )
 
![image](https://github.com/user-attachments/assets/c4530b13-f733-4a20-a52b-2d3a6964322d)

**Comment by m-kovalsky** [comment]
Does it work if you set ‘extended=False’?

If so, try running the tom.set_vertipaq_annotations() function against one of the models which didn’t work in the original bulk run.
________________________________
From: matiirueda ***@***.***>
Sent: Friday, August 30, 2024 7:50:10 PM
To: microsoft/semantic-link-labs ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/semantic-link-labs] BUG run_model_bpa_bulk (Issue #109)


Describe the bug

I was reviewing the results of running the loop across all workspaces, and for most of the datasets, it couldn't save data. It returns this error: "Model BPA failed for the 'Linaje' semantic model within the 'CIO' workspace. Single positional indexer is out-of-bounds."
Most of the datasets from the workspaces are giving me that error. Do we know what might be causing it?
Do you know what might be causing this? I'll mention it on Git.

This is my code for example for the workspace "CIO"

import sempy_labs as labs
from pyspark.sql import SparkSession
from sempy_labs import migration,report,directlake
from sempy_labs import lakehouse as lake
from sempy_labs.tom import connect_semantic_model

labs.run_model_bpa_bulk(extended= True, language = 'es-ES' , workspace='CIO' )

image.png (view on web)<https://github.com/user-attachments/assets/c4530b13-f733-4a20-a52b-2d3a6964322d>

**Comment by matiirueda** [comment]
Hi Michael, it worked by removing the parameter. Thanks.

On the other hand, an hour later I got this error: LivyHttpRequestFailure: Failed to send request to Livy. Please try again. If this issue still exists, please contact support.

Does this mean that the function calling the API has a rate limit per hour? If so, how long should I wait before calling it again?

**Comment by matiirueda** [comment]
Hi Michael, it worked by removing the parameter. Thanks.

On the other hand, an hour later I got this error: LivyHttpRequestFailure: Failed to send request to Livy. Please try again. If this issue still exists, please contact support.

Does this mean that the function calling the API has a rate limit per hour? If so, how long should I wait before calling it again?

**Comment by m-kovalsky** [comment]
I made a fix going into the next release which should fix the issue for the extended=True issue.

Hmm, you may want to split up the workspaces into groups of multiple sessions. I will also look into parallelizing this to gain efficiencies.
________________________________

**Comment by matiirueda** [comment]
Great, thanks for the improvements.

I have 70 workspaces and a total of 2500 semantic models. I created a loop to process each workspace, but it only manages to run about 14 workspaces. Do you think I should run several notebooks in parallel? Or is the Livy error due to too many API calls? If I add a 1-hour sleep and then continue with the remaining items in my catalog, would that solve the problem?

**Comment by m-kovalsky** [comment]
I’m not familiar with this error. Running several notebooks in parallel may be a more stable solution. Always good to test various options.
________________________________

**Comment by matiirueda** [comment]
Hi Michael, I think the Livy error is because the notebook gets filled with the output of the execution and runs out of memory. Is there a way to prevent the result from being displayed on the notebook screen and only save it to Delta?

The output is too large and hits Livy outputs limit. Please try to reduce your output or write it to a file.

Here's my code:

import pandas as pd
import sempy_labs as labs
from sempy_labs import migration, report, directlake
from sempy_labs import lakehouse as lake
from sempy_labs.tom import connect_semantic_model

# Obtener todos los datasets
all_datasets_df = spark.sql("SELECT DISTINCT Workspace_Name FROM VF_Auditoria_Modelos.all_items WHERE Type = 'SemanticModel'").toPandas()

# Iterar sobre cada nombre de área de trabajo y ejecutar la función
for index, row in all_datasets_df.iterrows():
    workspace_name = row['Workspace_Name']

    try:
        # Ejecutar la función con el área de trabajo actual
        labs.run_model_bpa_bulk(
            language='es-ES',
            workspace=workspace_name
        )
    except Exception:
        # Simplemente continuar con el siguiente workspace en caso de error
        continue

And I also tried:
CODE 2 

import pandas as pd
import sempy_labs as labs
from sempy_labs import migration, report, directlake
from sempy_labs import lakehouse as lake
from sempy_labs.tom import connect_semantic_model

# Obtener todos los datasets
all_datasets_df = spark.sql("SELECT DISTINCT Workspace_Name FROM VF_Auditoria_Modelos.all_items WHERE Type = 'SemanticModel' ORDER BY Workspace_Name DESC").toPandas()

# Preparar DataFrame para guardar resultados
results_df = pd.DataFrame(columns=['Workspace_Name', 'Result'])

# Iterar sobre cada nombre de área de trabajo y ejecutar la función
for index, row in all_datasets_df.iterrows():
    workspace_name = row['Workspace_Name']

    try:
        # Ejecutar la función con el área de trabajo actual
        result = labs.run_model_bpa_bulk(
            language='es-ES',
            workspace=workspace_name
        )
        # Agregar resultado al DataFrame
        results_df = results_df.append({
            'Workspace_Name': workspace_name,
            'Result': result
        }, ignore_index=True)

    except Exception as e:
        # Agregar error al DataFrame
        results_df = results_df.append({
            'Workspace_Name': workspace_name,
            'Result': f"Error: {e}"
        }, ignore_index=True)

# Escribir los resultados en Delta Lake
results_df.write.format("delta").save("/path/to/your/delta/table")

# Si deseas verificar que se escribió correctamente, puedes leer y mostrar un pequeño resumen
# read_df = spark.read.format("delta").load("/path/to/your/delta/table")
# display(read_df.head())



pero de todas formas me va mostrando el resultado en pantalla

But it still shows the result on the screen.

![image](https://github.com/user-attachments/assets/1bca1e0e-a420-4b98-943d-efe17345e9bf)

**Comment by matiirueda** [comment]
Error in pipline 
Notebook execution failed at Notebook service with http status code - '200', please check the Run logs on Notebook, additional details - 'Error name - InvalidHttpRequestToLivy, Error value - Submission failed due to error content =[] HTTP status code: 408. Trace ID: 0d96979d-e165-44db-9f39-e8bfcc3a655f.' : 

![image](https://github.com/user-attachments/assets/7297c294-95b6-4c4d-ac3e-1b9d15790d76)
Error when entering the notebook and viewing the output
![image](https://github.com/user-attachments/assets/3864221d-65e4-4d37-b377-bcd5970fbac6)


I found a solution to the Livy error. When iterating through each workspace, it accumulates in the notebook's memory, and at some point, it runs out of memory, causing the Livy error.

What I did was add clear_output(wait=True) to my code to clear the output after each loop.

However, I still have some workspaces that are very large, and since the output is cleared after each loop, it doesn't manage to run all the datasets.

It would be great if, in the next release, when running BPA in other areas, you could choose which dataset to run instead of all of them. This way, I could run only those that were left out due to memory issues. A parameter to hide the output on the screen would also be useful, so the notebook's memory doesn't get filled up.

**Comment by m-kovalsky** [comment]
This is fixed in [0.7.3](https://github.com/microsoft/semantic-link-labs/releases/tag/0.7.3).
