### ISSUE TITLE
DirectLake Schema Sync cannot add columns: directlake_schema_sync.py

### ISSUE THREAD

**Issue by jmolinacruz** [microsoft/semantic-link-labs#139]
**Describe the bug**
If you add the `add_column = True` argument for `directlake_schema_sync()`, the function will fail with a `'DataType' object has no attribute 'capitalize'` error. This happens because the `TOMWrapper.add_data_column()` within the function expects `data_type`  to be a string but is receiving a `Microsoft.AnalysisServices.Tabular.DataType` class instance instead.

**To Reproduce**
1. Use the following code with a Semantic Model where you know there is a missing column: 

       labs.directlake.direct_lake_schema_sync(modelName, workspace, add_to_model = True)

Changing the name of a column to test is enough, like adding an extra `s` at the end.

2. Console outputs the following Trace:

       407 import Microsoft.AnalysisServices.Tabular as TOM
       408 import System
       410 data_type = (
       --> 411     data_type.capitalize()
       412     .replace("Integer", "Int64")
       413     .replace("Datetime", "DateTime")
       414 )
       415 if summarize_by is None:
       416     summarize_by = "Default"

       AttributeError: 'DataType' object has no attribute 'capitalize'

**Expected behavior**
Refreshed schema for the model with the newly changed column in the Lakehouse

**Comment by m-kovalsky** [comment]
Thanks for reporting. Made a PR for the fix.

**Comment by m-kovalsky** [comment]
Fixed in [0.7.4](https://github.com/microsoft/semantic-link-labs/releases/tag/0.7.4).
