### ISSUE TITLE
Unable to update column info in semantic model via update_column function

### ISSUE THREAD

**Issue by blaine12100** [microsoft/semantic-link-labs#158]
**Describe the bug**

Trying to update columns in a semantic model via the update_colum function does not work

**To Reproduce**
1. Create a direct lake semantic model like : `labs.directlake.generate_direct_lake_semantic_model(dataset=dataset, lakehouse_tables=['mtcars_source', 'mtcars_dupe'], lakehouse='test', overwrite=True, lakehouse_workspace=workspace, workspace=workspace)`
2. Connect the semantic model via the connect_semantic model function in the tom package `with labs.tom.connect_semantic_model(dataset=dataset, readonly=False, workspace=workspace) as tom:`
4. Use the update_column function like : `tom.update_column(table_name='mtcars_dupe', column_name='model', description='Dummy description to test the working of this function mpg')`

**Expected behavior**
The update_column should update the necessary properties for a column in the semantic model without error.

**Screenshots**
![image](https://github.com/user-attachments/assets/c0ca7456-785f-4cfe-be9a-40e3de8809ee)

**Additional context**
Temporary Workaround is to modify the column attributes via a for loop to check if a column exists for a particular table, modify it's description, Ishidden attribute, formatting options etc. Not the recommended approach as it's very tedious. The output is surprising as the column exists for that given table and I'm able to modify some properties via the temp workaround.

**Comment by m-kovalsky** [comment]
See the ArgumentException at the end of the error message. There is such column 'mtcars_dupe'[model] in your model. Cannot update a column if it doesn't exist.

**Comment by blaine12100** [comment]
I've double checked this. The column exists in the lakehouse tables and also in the semantic model. I still get the same error message. If you see the add_relationship function, I'm able to create the relationship by using the model column in both tables (mtcars_source and mtcars_dupe). If the column didn't exist, the add_relationship function would have failed first.

**Comment by m-kovalsky** [comment]
Ah, I found the bug. I made a PR with the fix.

**Comment by blaine12100** [comment]
Will this be merged now or in a later release?

**Comment by m-kovalsky** [comment]
Will go into next week’s release.
________________________________

**Comment by blaine12100** [comment]
I did test it. It does indeed work. Thank you for fixing this.
Quick question: I cannot find an option to set the Is Nullable field via the update_column function. Are there plans to enable the user to set it via this function?

**Comment by m-kovalsky** [comment]
You can also update any such property using TOM directly (see code below). The update functions are for convenience (and mostly for setting properties such as data types which would require TOM.DataType.Int64 as an example.

```python
with connect_semantic_model(dataset='', workspace='', readonly=False) as tom:
    c = tom.model.Tables[''].Columns['']
    c.IsNullable = False
```

**Comment by blaine12100** [comment]
> You can also update any such property using TOM directly (see code below). The update functions are for convenience (and mostly for setting properties such as data types which would require TOM.DataType.Int64 as an example.
> 
> ```python
> with connect_semantic_model(dataset='', workspace='', readonly=False) as tom:
>     c = tom.model.Tables[''].Columns['']
>     c.IsNullable = False
> ```

When the functions were not working, this is the approach that I've used. I'll use that only then.

**Comment by m-kovalsky** [comment]
I’ll add this property to the update_column function for the next release
________________________________
