### ISSUE TITLE
update_direct_lake_partition_entity - Partition Entity Update Not Reflected in Semantic Model

### ISSUE THREAD

**Issue by Sumanapandranki7** [microsoft/semantic-link-labs#163]
We are experiencing an issue where the name of our lakehouse differs from the table name in our Semantic model. Despite successfully running the following method to update the partition entity, the changes are not reflected in the Semantic model:

```
directlake.update_direct_lake_partition_entity(
    newDatasetName,
    table_name= tablename,
    entity_name= lakehousetablename,
    workspace=workspace
)
```
Output: 🟢 The 'tablename' table in the 'newDatasetName' semantic model has been updated to point to the 'lakehousetablename' table in the 'lakehousename' lakehouse within the 'workspacename' workspace.workspace.

>> Output names are just for reference.

However, the update does not seem to be applied to the Semantic model as expected. Could someone help diagnose why the update is not reflected and how to resolve this issue?

**Comment by m-kovalsky** [comment]
Fixed in [0.8.5](https://github.com/microsoft/semantic-link-labs/releases/tag/0.8.5).
