### ISSUE TITLE
migrate_calc_tables_to_lakehouse returns an error

### ISSUE THREAD

**Issue by unme777** [microsoft/semantic-link-labs#173]
**Describe the bug**
Hi Michael, this is Ying from Canada. First, thank you very much for creating this great tool to facilitate DL migration!

The instruction is clear and easy to follow, however, when reaching to 
----> 4 migration.migrate_calc_tables_to_lakehouse(
      5     dataset = dataset_name,
      6     new_dataset = new_dataset_name,
      7     workspace = workspace_name,
      8     new_dataset_workspace = new_dataset_workspace_name,
      9     lakehouse = lakehouse_name,
     10     lakehouse_workspace = lakehouse_workspace_name
     11 )

we got some errors as below:

FabricHTTPException: 400 Bad Request for url: https://api.fabric.microsoft.com//v1/workspaces/36be636f-aa1f-4981-b7f9-2c7e7424047d/lakehouses/240a72f2-f4dd-42ea-b19a-1dd2716c0287/tables
Error: {"requestId":"223e5835-7115-445a-bb10-377936c982d6","errorCode":"UnsupportedOperationForSchemasEnabledLakehouse","message":"The operation is not supported for Lakehouse with schemas enabled."}
Headers: {'Content-Length': '192', 'Content-Type': 'application/json; charset=utf-8', 'x-ms-public-api-error-code': 'UnsupportedOperationForSchemasEnabledLakehouse', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'X-Frame-Options': 'deny', 'X-Content-Type-Options': 'nosniff', 'Access-Control-Expose-Headers': 'RequestId', 'request-redirected': 'true', 'home-cluster-uri': 'https://wabi-us-north-central-c-primary-redirect.analysis.windows.net/', 'RequestId': '223e5835-7115-445a-bb10-377936c982d6', 'Date': 'Thu, 26 Sep 2024 20:41:54 GMT'}

![image](https://github.com/user-attachments/assets/4ff18964-4756-46de-bb05-5854cbed6e0c)
![image](https://github.com/user-attachments/assets/a615c021-1857-4160-9dc9-31680a3eb692)
![image](https://github.com/user-attachments/assets/771f3719-1884-40c8-912f-add551172055)

We have tried a couple of times, "migrate_tables_columns_to_semantic_model" and " migrate_field_parameters" worked, "migrate_model_objects_to_semantic_model" didn't return an error but relationships and measures didn't show up after running the codes. 

Do you have any suggestions how we could fix the issue? Thanks in advance for your help!

Once again, it's a great tool:)

**Comment by m-kovalsky** [comment]
Do you have schemas enabled for the lakehouse? It appears that if you do, this API does not work (which is a bug in the actual API).

**Comment by m-kovalsky** [comment]
I can confirm this is a known limitation with schema-enabled lakehouses. Hoping this functionality will be enabled in the near future.

https://learn.microsoft.com/en-us/fabric/data-engineering/lakehouse-schemas#public-preview-limitations

**Comment by unme777** [comment]
@m-kovalsky Thanks a lot for taking time look the issue. I will create a new lakehouse without schema enabled feature to test migration. Will let you know how it goes. :)

**Comment by unme777** [comment]
Hi @m-kovalsky, 

This time I create a lakehouse without schema enabled, and was able to migrate 41% of my semantic model. All regular tables and columns are converted to direct lake mode but measures, field parameters and relationships are not working. 

I noticed all field parameters are interpreted as "auto-datetime table" and didn't return as expected.
![image](https://github.com/user-attachments/assets/fa9b2bd0-ddaf-416f-ab02-94843867b81e)

These are all the messages returned as the end:
![image](https://github.com/user-attachments/assets/88608773-4f29-4c52-aa5d-ff9775b75a0d)

![image](https://github.com/user-attachments/assets/10f591ee-1b42-4ffb-be1c-107e74b57791)

![image](https://github.com/user-attachments/assets/9e828b3c-c11b-41fc-9352-ef824d94b2ec)

0_metrics and Slicer_value are two calculated tables that store all measures by folders (organized using tabular editor), they are migrated but are empty.

![image](https://github.com/user-attachments/assets/0c07d020-ae11-44f1-8626-e5ce0d007052)

Do you have any suggestion how I can fix it? 

Thanks a lot in advance!

Ying

**Comment by m-kovalsky** [comment]
The root of your problem is that you have several auto-date tables. These are calculated tables which are not migrated. You need to go back to Power BI Desktop and disable these before create a proper date table in your model before you can use this migration solution.
