### ISSUE TITLE
Can no longer create semantic model in other workspace

### ISSUE THREAD

**Issue by paulienleeuwenburgh** [microsoft/semantic-link-labs#174]
Previously I could, now I can no longer create a semantic model using directlake.generate_direct_lake_semantic_model in a **different** workspace than the WS that is hosting the lakehouse that I've attached to my notebook and that contains the deltatables that I want to add to the semantic model.

The error suggest that it is searching for the delta-tables in the workspace where I want my store my semantic model, instead of in the the (default) lakehouse that I attached to my notebook.

Could you check?

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[46], line 1
----> 1 labs.directlake.generate_direct_lake_semantic_model(
      2     dataset =  "csm",\
      3     lakehouse_tables = ['table1'],\
      4     workspace = "csm_hostingws",\
      5     lakehouse = None,\
      6     lakehouse_workspace = None,\
      7     overwrite = False,\
      8     refresh = False\
      9     )

File /nfs4/pyenv-5483a8a1-9a01-4c8a-bc6e-018b990876d1/lib/python3.10/site-packages/sempy/_utils/_log.py:273, in mds_log.<locals>.get_wrapper.<locals>.log_decorator_wrapper(*args, **kwargs)
    270     raise
    272 try:
--> 273     result = func(*args, **kwargs)
    275     # The invocation for get_message_dict moves after the function
    276     # so it can access the state after the method call
    277     message.update(extractor.get_completion_message_dict(result, arg_dict))

File /nfs4/pyenv-5483a8a1-9a01-4c8a-bc6e-018b990876d1/lib/python3.10/site-packages/sempy_labs/directlake/_dl_helper.py:121, in generate_direct_lake_semantic_model(dataset, lakehouse_tables, workspace, lakehouse, lakehouse_workspace, overwrite, refresh)
    119 for t in lakehouse_tables:
    120     if t not in dfLT["Table Name"].values:
--> 121         raise ValueError(
    122             f"{icons.red_dot} The '{t}' table does not exist as a delta table in the '{lakehouse}' within the '{workspace}' workspace."
    123         )
    125 dfLC = get_lakehouse_columns(lakehouse=lakehouse, workspace=lakehouse_workspace)
    126 expr = get_shared_expression(lakehouse=lakehouse, workspace=lakehouse_workspace)

ValueError: 🔴 The 'table1' table does not exist as a delta table in the 'None' within the 'csm_hostingws' workspace.

**Comment by paulienleeuwenburgh** [comment]
To be complete:
The table that I want to add to the semantic model is in the lakehouse attached to the notebook and is a delta table.

**Comment by m-kovalsky** [comment]
This will be fixed in PR #175
