### ISSUE TITLE
Migration to Direct Lake ValueError in Function migration.refresh_calc_tables

### ISSUE THREAD

**Issue by TK-Fab** [microsoft/semantic-link-labs#201]
** We are running the 'Migration to Direct Lake' Notebook against our old datasets and semantics model (import/DQ).  The notebook process is super easy to follow and we got resolved a lot of our legacy data issues to ensure it is supported by Direct Lake Semantic Model. 
However we got stuck at line 40 after invoke
migration.refresh_calc_tables(dataset = new_dataset_name, workspace = new_dataset_workspace_name) when Python give us a ValueError inside the functions line 126.

Please help...please help 
Thanks Trang

![Image](https://github.com/user-attachments/assets/f6645757-a862-418e-b26e-b6407ee6b13f)
![Image](https://github.com/user-attachments/assets/b4fe4b7f-2bcc-438d-a84b-95904c993997)

**Comment by m-kovalsky** [comment]
Hmm, the error message is not particularly useful. If you run the same refresh_semantic_model function in a different cell does it give you the same error message? Sometimes the service needs a bit of a pause to determine the new model exists before it can call the refresh. You should also make sure that the entity names in the partitions align with the lakehouse. If any do not align, the refresh will fail.

**Comment by TK-Fab** [comment]
Thank you so much for your response.  We will check and also we will put in a pause and check. 
Truly appreciate.
Trang

**Comment by m-kovalsky** [comment]
Are you still facing issues here or can we close the issue?

**Comment by TK-Fab** [comment]
yes Michael, this issue can be closed. Thank youOn 10 Dec 2024, at 17:11, m-kovalsky ***@***.***> wrote:﻿
Are you still facing issues here or can we close the issue?
