### ISSUE TITLE
list_deployment_pipeline_stages is returning an error for a pipeline that exists

### ISSUE THREAD

**Issue by MikeCarlo** [microsoft/semantic-link-labs#212]
**Describe the bug**
When using the function `list_deloyment_pipeline_stages('Text of Pipeline Name') an error is returned

**Screenshots**
see error from command

![Image](https://github.com/user-attachments/assets/e069056f-6ef0-481b-8cf0-4a96a15a2a65)

Deployment pipeline does exist and has two environments Dev and Test, but no workspace for Prod

![Image](https://github.com/user-attachments/assets/5d08ed73-f931-43c0-96ef-e52a44ba71b2)

**Comment by m-kovalsky** [comment]
See [0.8.4](https://github.com/microsoft/semantic-link-labs/releases/tag/0.8.4).
