### ISSUE TITLE
Missing non admin function list_workspaces()

### ISSUE THREAD

**Issue by MikeCarlo** [microsoft/semantic-link-labs#213]
**Describe the bug**
Seems like there should be a list_workspaces() function that will list all workspaces that I have access to see. 

This is referenced in the admin.list_workspaces() and references that there is a non admin version
[admin.list_workspaces](https://semantic-link-labs.readthedocs.io/en/latest/sempy_labs.admin.html#sempy_labs.admin.list_workspaces)

![Image](https://github.com/user-attachments/assets/9830654e-cdaa-4656-9769-4ed4c3acf907)

Is this a missing function or did it get deleted?

**Comment by m-kovalsky** [comment]
The non-admin version of list_workspaces is in semantic link. I’m not recreating functions that already exist in semantic link so best to check there if you can’t find it in labs.

‘’’python
import sempy.fabric as fabric

fabric.list_workspaces()
‘’’
________________________________
From: Mike Carlo ***@***.***>
Sent: Wednesday, October 16, 2024 7:36:23 AM
To: microsoft/semantic-link-labs ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/semantic-link-labs] Missing non admin function list_workspaces() (Issue #213)


Describe the bug
Seems like there should be a list_workspaces() function that will list all workspaces that I have access to see.

This is referenced in the admin.list_workspaces() and references that there is a non admin version
admin.list_workspaces<https://semantic-link-labs.readthedocs.io/en/latest/sempy_labs.admin.html#sempy_labs.admin.list_workspaces>

image.png (view on web)<https://github.com/user-attachments/assets/9830654e-cdaa-4656-9769-4ed4c3acf907>

Is this a missing function or did it get deleted?
