### ISSUE TITLE
Get Lakehouse tables API not working when using Lakehouses with Schema

### ISSUE THREAD

**Issue by MikeCarlo** [microsoft/semantic-link-labs#214]
**Describe the bug**
The current function for lakehouse.get_lakehouse_tables supports reading tables from lakehouses with no schema enabled.

If there is a schema on the lakehouse the api `/workspaces/GUID/lakehouse/GUID/tables` fails with the following message

api-error-code = 'UnsupportedOperationForSchemasEnabledLakehouse'

A 400 error is returned. 

![Image](https://github.com/user-attachments/assets/9df32fe6-c18e-4648-ba56-db170ec0f0cb)

**Comment by m-kovalsky** [comment]
See issue #173.
