### ISSUE TITLE
Incorrect Description in BPA Rules for rule "Visible objects with no description"

### ISSUE THREAD

**Issue by thedaxshepherd** [microsoft/semantic-link-labs#225]
**Describe the bug**
In the _model _bpa_rules.py file, an incorrect description is assigned to one of the rules.
The rule "Visible objects with no description" has the description of "Calculation groups have no function unless they have calculation items." This belongs to the rule "Calculation groups with no calculation items" above it in the file. A new description is needed for "Visible objects with no description".

**Comment by m-kovalsky** [comment]
This has been completed and will be available in the next release.
________________________________

**Comment by thedaxshepherd** [comment]
Is the change to add a description rule "Calculation groups with no calculation items" in the current code, or does it still need to be merged? I only ask because I do not see the change in the current code base for the "Calculation Group" description. I built the Wheel file and tested the change to the "Visible Objects" rule. I was going to test the "Calculation Group" rule but did not see the code change.

**Comment by m-kovalsky** [comment]
Fixed in [0.8.4](https://github.com/microsoft/semantic-link-labs/releases/tag/0.8.4).
