### ISSUE TITLE
list_activity_events is not considering user_id_filter and activity_filter filter.

### ISSUE THREAD

**Issue by Jai-Prakash-HU** [microsoft/semantic-link-labs#226]
**Describe the bug**
list_activity_events is not considering user_id_filter and activity_filter filter.

df_activity_events = labs.admin.list_activity_events(
    start_time =  "2024-10-19T10:00:00", 
    end_time =  "2024-10-19T10:10:00", 
    activity_filter="GetWorkspaces",
    user_id_filter="xyz@abc.com",)

**Expected behavior**
it should return only one activity for and only for given user. But it is returning many activities and for all the user in the given time window.

**Comment by m-kovalsky** [comment]
Fixed in [0.8.4](https://github.com/microsoft/semantic-link-labs/releases/tag/0.8.4).
