### ISSUE TITLE
KeyError: 'Referenced Object Type' when running labs.list_semantic_model_object_report_usage(dataset='DS_Contoso', extended=True, include_dependencies=True)

### ISSUE THREAD

**Issue by ndswaef** [microsoft/semantic-link-labs#229]
**Describe the bug**
KeyError: 'Referenced Object Type' when running labs.list_semantic_model_object_report_usage(dataset='DS_Contoso', extended=True, include_dependencies=True)

Function works when putting include_dependencies=False

**Screenshots**
![Image](https://github.com/user-attachments/assets/1063ba0f-e817-479e-9f6d-0072eb786d1c)

**Comment by m-kovalsky** [comment]
Fixed in [0.8.4](https://github.com/microsoft/semantic-link-labs/releases/tag/0.8.4).
