### ISSUE TITLE
Decimal data types only considered for (38,18) or (19,4) in "icon.py"

### ISSUE THREAD

**Issue by Benjiman89** [microsoft/semantic-link-labs#232]
**Describe the bug**
When running "add_table_to_direct_lake_semantic_model" it errors when Lakehouse tables have decimal data types that are not either decimal(38,18) or decimal(19,4) due to the following code inside icons.py (https://github.com/microsoft/semantic-link-labs/blob/main/src/sempy_labs/_icons.py):

data_type_mapping = {
    "string": "String",
    "int": "Int64",
    "tinyint": "Int64",
    "smallint": "Int64",
    "bigint": "Int64",
    "boolean": "Boolean",
    "timestamp": "DateTime",
    "date": "DateTime",
    **"decimal(38,18)": "Decimal",
    "decimal(19,4)": "Decimal",**
    "double": "Double",
    "float": "Double",
}

**To Reproduce**
Run "add_table_to_direct_lake_semantic_model" it errors when Lakehouse tables have decimal data types other than decimal(38,18) or decimal(19,4)

**Expected behavior**
No error message

**Screenshots**
![Image](https://github.com/user-attachments/assets/d5a2d5e5-6fb8-419d-82b9-295a28413784)

**Comment by m-kovalsky** [comment]
Thanks for reporting. This will be fixed in the next release.

**Comment by m-kovalsky** [comment]
Fixed in [0.8.4](https://github.com/microsoft/semantic-link-labs/releases/tag/0.8.4).
