### ISSUE TITLE
get_direct_lake_guardrails() returns Fabric SKU not Fabric SKUs as a column name.

### ISSUE THREAD

**Issue by MitchSS** [microsoft/semantic-link-labs#233]
get_direct_lake_guardrails() returns Fabric SKU not Fabric SKUs as a column name. Therefore, get_lakehouse_tables() fails when using extended=True.

get_directlake_guardrails_for_sku is also affected.

**Comment by m-kovalsky** [comment]
Fixed in [0.8.4](https://github.com/microsoft/semantic-link-labs/releases/tag/0.8.4).
