### ISSUE TITLE
Support for custom fonts in  theme_json

### ISSUE THREAD

**Issue by Klaphat** [microsoft/semantic-link-labs#235]
The theme_json only supports fonts included in Power BI Desktop. 

Most larger companies have their own design manuels with their own fonts. For instance https://cphhalf.dk/ uses the font "NB International Pro Regular". 

Update the theme_json to be able to take a link to a custom font. This theme only works if the font is installed on the computer

{
  "name": "Custom",
  "textClasses": {
    "label": {
      "fontFace": "NB International Pro Regular",
      "fontSize": 10,
      "color": "#453740"
    },
    "callout": {
      "fontFace": "NB International Pro Regular",
      "fontSize": 40,
      "color": "#453740"
    },
    "title": {
      "fontFace": "NB International Pro Regular",
      "fontSize": 10,
      "color": "#453740"
    },
    "header": {
      "fontFace": "NB International Pro Regular",
      "fontSize": 10,
      "color": "#453740"
    }
  },
  "visualStyles": {
    "page": { "*": { "outspace": [ { "color": { "solid": { "color": "#FFFFFF" } } } ] } }
  }
}

The font only need to installed on the computer used for development. When the report is published to Power BI services every one can see the correct font.

**Comment by m-kovalsky** [comment]
Did you try downloading this font and then setting the theme for a report using the function?

**Comment by Klaphat** [comment]
Yes, it defaults to a standard font if a non-standard font is in the theme.json file. Another issue I found is that you can only set a theme once. The second try always gives the following error message: 

FabricHTTPException: 409 Conflict for url: https://api.fabric.microsoft.com//v1/workspaces/46413c1c-3780-4d94-8889-451c64c0d67d/reports/d648b4b4-6265-4d32-92f5-75b385940df5/updateDefinition
Error: {"requestId":"685e8dbf-35d8-43c0-a4a0-4e4a98c0e971","errorCode":"DuplicateDefinitionParts","message":"There are multiple parts with same path in the item definition."}
Headers: {'Cache-Control': 'no-store, must-revalidate, no-cache', 'Pragma': 'no-cache', 'Transfer-Encoding': 'chunked', 'Content-Type': 'application/json; charset=utf-8', 'x-ms-public-api-error-code': 'DuplicateDefinitionParts', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'X-Frame-Options': 'deny', 'X-Content-Type-Options': 'nosniff', 'RequestId': '685e8dbf-35d8-43c0-a4a0-4e4a98c0e971', 'Access-Control-Expose-Headers': 'RequestId', 'Date': 'Thu, 31 Oct 2024 08:55:50 GMT'}

**Comment by m-kovalsky** [comment]
I don't think the custom fonts are actually supported. Where is one supposed to save the font file in order for this to work?

As to the issue that is strange as in the demo I gave I switched the theme file twice with no issues.

**Comment by Klaphat** [comment]
It's possible to use all fonts located on the computer when assigning a theme in Power BI Desktop. I have installed a custom font and this can be seen by all users in Power BI services after the report has been published.

The location of fonts on the computer is here:
![Image](https://github.com/user-attachments/assets/53920bcd-26ab-40f1-abd2-2357c79c8913)

I might have something to do with the theme file I'm using that's causing a bug. If I upload this as JSON to a datalake and use the set_theme function it works the first time, but errors out the second:

{
  "name": "Custom",
  "dataColors": [
    "#6E6EFF",
    "#5BFE60",
    "#FFFA1E",
    "#91F8FF",
    "#FFA0FF",
    "#FFA082",
    "#000000",
    "#453740",
    "#3599B8",
    "#DFBFBF",
    "#4AC5BB",
    "#5F6B6D",
    "#FB8281",
    "#F4D25A",
    "#7F898A",
    "#A4DDEE",
    "#FDAB89",
    "#B687AC",
    "#28738A",
    "#A78F8F",
    "#168980",
    "#293537",
    "#BB4A4A",
    "#B59525",
    "#475052",
    "#6A9FB0",
    "#BD7150",
    "#7B4F71",
    "#1B4D5C",
    "#706060",
    "#0F5C55",
    "#1C2325"
  ],
  "bad": "#FFA082",
  "neutral": "#FFFA1E",
  "good": "#5BFE60",
  "minimum": "#FFA082",
  "center": "#FFFA1E",
  "maximum": "#5BFE60",
  "textClasses": {
    "label": {
      "fontFace": "Wingdings",
      "fontSize": 10,
      "color": "#453740"
    },
    "callout": {
      "fontFace": "Wingdings",
      "fontSize": 40,
      "color": "#453740"
    },
    "title": {
      "fontFace": "Wingdings",
      "fontSize": 10,
      "color": "#453740"
    },
    "header": {
      "fontFace": "Wingdings",
      "fontSize": 10,
      "color": "#453740"
    }
  },
  "visualStyles": {
    "page": {
      "*": {
        "outspace": [
          {
            "color": {
              "solid": {
                "color": "#FFFFFF"
              }
            }
          }
        ]
      }
    }
  }
}

**Comment by m-kovalsky** [comment]
I made a fix which will not cause an error if setting the theme twice. if the theme has the same name it will now simply overwrite the existing custom theme.

**Comment by m-kovalsky** [comment]
The aforementioned fix is available in [0.8.5](https://github.com/microsoft/semantic-link-labs/releases/tag/0.8.5).

**Comment by Klaphat** [comment]
> The aforementioned fix is available in [0.8.5](https://github.com/microsoft/semantic-link-labs/releases/tag/0.8.5).

Cool. And what about support for custom fonts?

**Comment by m-kovalsky** [comment]
I don't think this is supported for the PBI service. It will likely work in desktop because you have the font installed on your computer but will not work in the service unless the font is installed on those computers.

**Comment by Klaphat** [comment]
If the font is hosted somewhere (for instance https://fonts.google.com/) then it could be made possible to get the style from the URL. But probably a bigger implementation. I just need the possibility of custom fonts for this to really useful :)

**Comment by m-kovalsky** [comment]
As I said, I don’t think this is supported in the power bi service. Closing this for now.
