### ISSUE TITLE
Script out semantic model

### ISSUE THREAD

**Issue by GilbertQue** [microsoft/semantic-link-labs#24]
Hi there

I really like the new sempy_labs module. 

Would it be possible to create the object to script out and or replace the semantic model?

The reason is sometimes I want to get a copy of the semantic model. And other times I want to do a bulk replace and this makes it a lot easier.

**Comment by m-kovalsky** [comment]
Thanks Gilbert. Are you trying to script out the entire model? Have you tried the [get_semantic_model_bim](https://semantic-link-labs.readthedocs.io/en/stable/sempy_labs.html#sempy_labs.get_semantic_model_bim) function and [create_semantic_model_from_bim](https://semantic-link-labs.readthedocs.io/en/stable/sempy_labs.html#sempy_labs.create_semantic_model_from_bim) functions? If this doesn't help, please give an example of what you are trying to do.

**Comment by GilbertQue** [comment]
Hi Michael, I somehow managed to miss that. I can get the information I need from the [get_semantic_model_bim](https://semantic-link-labs.readthedocs.io/en/stable/sempy_labs.html#sempy_labs.get_semantic_model_bim). I tried it with another error which I will a separate issue so that others who are searching can find this helpful.
