### ISSUE TITLE
Migration to Direct Lake - DateTime columns

### ISSUE THREAD

**Issue by carlyrg** [microsoft/semantic-link-labs#243]
Using the notebook to convert import mode semantic model to Direct Lake in Fabric I'm getting  number of unsupported items related to relationships between columns being of DateTime format. However they are defined as 'Date' in power bi and formatted as short date in the model and even in the SQL source table they are defined as a 'Date' data type. How do I get these columns to be recognized as Dates so the relationships can be created?

![Image](https://github.com/user-attachments/assets/f7b6612c-aa03-4805-b31f-58a3fd7e3d52)

![Image](https://github.com/user-attachments/assets/14d56dbc-ce31-462f-919b-269c2940422f)

**Comment by m-kovalsky** [comment]
As of 0.8.4 this restriction is removed.
________________________________
From: Carly Gerhart ***@***.***>
Sent: Wednesday, October 30, 2024 4:25:10 PM
To: microsoft/semantic-link-labs ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/semantic-link-labs] Migration to Direct Lake - DateTime columns (Issue #243)


Using the notebook to convert import mode semantic model to Direct Lake in Fabric I'm getting number of unsupported items related to relationships between columns being of DateTime format. However they are defined as 'Date' in power bi and formatted as short date in the model and even in the SQL source table they are defined as a 'Date' data type. How do I get these columns to be recognized as Dates so the relationships can be created?

image.png (view on web)<https://github.com/user-attachments/assets/f7b6612c-aa03-4805-b31f-58a3fd7e3d52>

image.png (view on web)<https://github.com/user-attachments/assets/14d56dbc-ce31-462f-919b-269c2940422f>

**Comment by carlyrg** [comment]
Thank you for the response and update

**Comment by m-kovalsky** [comment]
[0.8.4](https://github.com/microsoft/semantic-link-labs/releases/tag/0.8.4)
