### ISSUE TITLE
Which application user is configured for each semantic model in the gateway

### ISSUE THREAD

**Issue by matiirueda** [microsoft/semantic-link-labs#254]
Hello, I need to know if there is a function in Semantic Lab that allows me to see which application user is configured for the gateway in the service.

Currently, I have several application users that can be selected in the gateway, and I would like to know if there is a way to extract which application user is configured in the gateway for each ID of the semantic model.

![Image](https://github.com/user-attachments/assets/f9127b61-6d76-4713-8379-202e4d541726)

**Comment by m-kovalsky** [comment]
I think this should be the one [list_connections](https://semantic-link-labs.readthedocs.io/en/stable/sempy_labs.html#sempy_labs.list_connections)

**Comment by m-kovalsky** [comment]
It will likely be one of these APIs. I don't think I have wrapped either of these yet. List_connections doesn't take any parameters as I don't think the API behind it takes any parameters.

https://learn.microsoft.com/en-us/rest/api/power-bi/datasets/get-datasources-in-group

https://learn.microsoft.com/en-us/rest/api/power-bi/datasets/get-gateway-datasources-in-group
________________________________

**Comment by m-kovalsky** [comment]
I found a bug in the API request which was causing this issue. The fix will go out in 0.8.8.

**Comment by m-kovalsky** [comment]
This is fixed in [0.8.8](https://github.com/microsoft/semantic-link-labs/releases/tag/0.8.8).[](url)
