### ISSUE TITLE
Add Last updated Date (for structural change) for Workspace and dataset in the function  labs.admin.list_datasets and labs.admin.list_workspaces

### ISSUE THREAD

**Issue by Jai-Prakash-HU** [microsoft/semantic-link-labs#255]
Let's assume I want to see when my dataset or workspace was updated (someone made some structural change) changes to workspace or dataset.
It will help me to narrow down the list of workspace/dataset where I need to focus for BPA and Vertipaq analysis.

I have 5000 workspace and 50k Dataset, so, I do not want to analyze all workspace or dataset every time. So having the last structural update date will help me to narrow down the list to be analyzed.

**Comment by m-kovalsky** [comment]
The api behind this function does not show the last changed date/time of the workspace.

**Comment by m-kovalsky** [comment]
You can use this [function](https://semantic-link-labs.readthedocs.io/en/latest/sempy_labs.admin.html#sempy_labs.admin.list_modified_workspaces)

**Comment by Jai-Prakash-HU** [comment]
Yes, for workspace it is fine. But I am looking for something for Dataset. Do we have any function which will give me last updated time if any dataset gets updated (not refreshed). I am looking for updated time for structural change. 

Currently I am managing it by running labs.admin.list_activity_events for below case in loop. I am not sure below lists cover all the changes or not. Also, if dataset is edited by EditDatasetFromExternalApplication then I do not get dataset detail. 


dataset_change_activity = [
    'CreateDatasetFromExternalApplication',
    'EditDatasetFromExternalApplication',
    'CreateDataset',
    'EditDataset',
    'UpdateDataset',
    'Import',
    'CreateDatasetByQuickShare',
    'EditDatasetProperties'
]



Could you please give some function which is better to find the list of updated datasets than above method. 

Use case is I want to automate the vertipaq and BPA process but also, I want to narrow down the list of workspaces for which it will be running.

**Comment by m-kovalsky** [comment]
For semantic models you must get this from a DMV. Maybe TMSCHEMA_MODEL? One of the dmvs has a ‘modified date’ for the model. Or the scanner API (which is an admin api). I have a wrapper function for that api which I haven’t released but it’s in the library. The reason this isn’t fully released yet is because I’m working on enhancements.

from sempy_labs.admin import scan_workspaces

**Comment by m-kovalsky** [comment]
Ah you could actually use this. Just check to see the accuracy of the value.

```
import sempy.fabric as fabric
fabric.list_datasets(additional_xmla_properties=['Model.ModifiedTime'])
```
