### ISSUE TITLE
Add Domain Name to workspace detail in the function labs.admin.list_workspaces

### ISSUE THREAD

**Issue by Jai-Prakash-HU** [microsoft/semantic-link-labs#256]
It would be good if we can get domain name while running this function.

**Comment by m-kovalsky** [comment]
domain name is not an output of the API behind the admin.list_workspaces function. There is a separate function (with a separate API) for this:

[admin.list_domain_workspaces](https://semantic-link-labs.readthedocs.io/en/stable/sempy_labs.admin.html#sempy_labs.admin.list_domain_workspaces)

**Comment by m-kovalsky** [comment]
Just checking in - can we close this issue?

**Comment by Jai-Prakash-HU** [comment]
Yes, we can close this.
