### ISSUE TITLE
sempy_labs.get_semantic_model_bim - Cannot get dataset from other App Workspaces

### ISSUE THREAD

**Issue by GilbertQue** [microsoft/semantic-link-labs#26]
Hi Michael,

Thanks once again for all your amazing work and assistance.

I tried the sempy_labs.get_semantic_model_bim which works fine if I am using a dataset in the same workspace. 

When I try and access a dataset in a different app workspace I get the following error below.

The thing to note is that to matter which App Workspace I change it to, it always errors with the same ID "ValueError: There's no item with the ID '260cc545-9a59-45a7-9897-fb705d4bc4ae'"

![image](https://github.com/microsoft/semantic-link-labs/assets/72849240/392c1542-f426-4755-8145-db1edc54f737)

Here is the code that I am using:

````
# Script out Database

dataset_name =  "4.Security"
workspace_name = "Presso's"

df = sempy_labs.get_semantic_model_bim(dataset = dataset_name, workspace = workspace_name , save_to_file_name = "/lakehouse/default/Files/mymodel.bim")
```

**Comment by m-kovalsky** [comment]
This appears to be because the workspace in which the dataset exists is different than the workspace in which the lakehouse (attached to the notebook) exists. Is that the case?

**Comment by GilbertQue** [comment]
Hi Michael,

Yes, that is correct. I thought when I put in the workspace and the dataset in the same workspace it should then return the model.bim?

Ideally, I want to run a notebook in Fabric enabled App Workspace but get the model.bim from a Power BI Premium Per user app workspace.

**Comment by m-kovalsky** [comment]
The error doesn't occur regarding the dataset's workspace. It occurs because the lakehouse's workspace is different. I can add a parameter for the lakehouse workspace and that should take care of it. Right now it's trying to look up the lakehouse within the dataset's workspace and it can't find it so it yields an error.

**Comment by m-kovalsky** [comment]
Also, I believe I will have to update this function as I am only seeing TMDL files (no .bim) from the API that this function uses.

**Comment by GilbertQue** [comment]
That would be great to have the additional parameter. I'm happy to just keep the TMDL format. Thank you

**Comment by m-kovalsky** [comment]
The additional parameter will be in the next version. I think I will also add another parameter which will allow either getting the bim or getting the tmdl files. Will probably have to update the function name in that case to something like 'get_semantic_model_definition'.

**Comment by GilbertQue** [comment]
That would be awesome thank you!

**Comment by m-kovalsky** [comment]
Try [0.6.0](https://github.com/microsoft/semantic-link-labs/releases/tag/0.6.0).

**Comment by GilbertQue** [comment]
Awesome thanks for getting this done I appreciate it and it will help me and my customers!
