### ISSUE TITLE
Error in run_model_bpa_bulk documentation

### ISSUE THREAD

**Issue by plorenc** [microsoft/semantic-link-labs#260]
There is no dataset parameter in the run_model_bpa_bulk  function.
Version: 0.8.4

def run_model_bpa_bulk(
    rules: Optional[pd.DataFrame] = None,
    extended: bool = False,
    language: Optional[str] = None,
    workspace: Optional[str | List[str]] = None,
    skip_models: Optional[str | List[str]] = ["ModelBPA", "Fabric Capacity Metrics"],
):
    """
    Runs the semantic model Best Practice Analyzer across all semantic models in a workspace (or all accessible workspaces).
    Saves (appends) the results to the 'modelbparesults' delta table in the lakehouse attached to the notebook.
    Default semantic models are skipped in this analysis.

    Parameters
    ----------
    dataset : str
        Name of the semantic model.

**Comment by m-kovalsky** [comment]
Fixed in [0.8.5](https://github.com/microsoft/semantic-link-labs/releases/tag/0.8.5).
