### ISSUE TITLE
Add parameter to add_calculation_group to specify the calculation group column name please

### ISSUE THREAD

**Issue by DataZoeMS** [microsoft/semantic-link-labs#261]
I like my calculation group column to be a specific name, so it would be great to just say what I want that to be when creating the calc group. Thanks!

**Comment by m-kovalsky** [comment]
Added in [0.8.5](https://github.com/microsoft/semantic-link-labs/releases/tag/0.8.5).

**Comment by DataZoeMS** [comment]
Wonderful, thank you!
