### ISSUE TITLE
Ability to run semantic-labs on Azure Databricks notebooks

### ISSUE THREAD

**Issue by cabelo-moreno** [microsoft/semantic-link-labs#262]
We are considering to use Fabric Capacities, but today we have some Premium Capacities, and Databricks workspaces for the datalake.
We would like to connect them, run BPA on premium capacities and save the results to datalake on Databricks

**Comment by m-kovalsky** [comment]
You can run semantic link/labs on premium capacities if you have Fabric enabled. We do not support running semantic link/labs outside of a Fabric environment.
