### ISSUE TITLE
run_model_bpa_bulk doesn't throw error if I do not have access to workspace.

### ISSUE THREAD

**Issue by Jai-Prakash-HU** [microsoft/semantic-link-labs#267]
Ideally if I do not have access to a workspace what I am passing as parameter then it should throw an error. But it shows process completed without creating and saving any result.

I am trying to automate a solution which takes the list of workspaces as input and runs run_model_bpa_bulk in loop. But it creates confusion when it completes the process without generating any result. 

![Image](https://github.com/user-attachments/assets/e9a58cdc-85ff-4eee-bd6c-f35b122ee650)

**Comment by m-kovalsky** [comment]
Fixed in [0.8.5](https://github.com/microsoft/semantic-link-labs/releases/tag/0.8.5).
