### ISSUE TITLE
run_model_bpa Running Forever and Not Completing for Certain Datasets

### ISSUE THREAD

**Issue by Jai-Prakash-HU** [microsoft/semantic-link-labs#274]
run_model_bpa is running from last many hours. Please check the scenarios as below. 

1. Tried multiple times, this particular dataset never gets completed. 
2. Tried with both function run_model_bpa and run_model_bpa_bulk
3. published dadatset to diffrent workspace, same result 
4. Dataset is very simple, It's size is 2 MB.  Large semantic model storage format is disabled. Sensitivity is internal. Total number of tables are 2 and few calculated tables. 
6. I tried 7-8 times on different days same result. 
7. It doesn't throw any error, just keeps running.
8. Same function in the same connection instance running fine.
9. I can download dataset, it looks fine.  I published it to different workspace with different name, but same issue.  

![Image](https://github.com/user-attachments/assets/e18bcb42-577d-48be-ab48-85bd04da114d)

![Image](https://github.com/user-attachments/assets/19d8f45e-f03e-4d72-a192-e4028e414402)

**Comment by m-kovalsky** [comment]
Is the model processed? Can you run labs.get_model_calc_dependencies() against that semantic model? Can you connect using the Tom wrapper:

with connect_semantic_model(dataset='', workspace='') as tom:

________________________________
From: Jai-Prakash-HU ***@***.***>
Sent: Tuesday, November 12, 2024 7:43:13 PM
To: microsoft/semantic-link-labs ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/semantic-link-labs] run_model_bpa running too much time for few dataset. (Issue #274)


run_model_bpa is running from last many hours. Please check the scenarios as below.

  1.  Tried multiple times, this particular dataset never gets completed.
  2.  Tried with both function run_model_bpa and run_model_bpa_bulk
  3.  published dadatset to diffrent workspace, same result
  4.  Dataset is very simple, It's size is 2 MB. Large semantic model storage format is disabled. Sensitivity is internal. Total number of tables are 2 and few calculated tables.
  5.  I tried 7-8 times on different days same result.
  6.  It doesn't throw any error, just keeps running.
  7.  Same function in the same connection instance running fine.
  8.  I can download dataset, it looks fine. I published it to different workspace with different name, but same issue.

image.png (view on web)<https://github.com/user-attachments/assets/e18bcb42-577d-48be-ab48-85bd04da114d>

image.png (view on web)<https://github.com/user-attachments/assets/19d8f45e-f03e-4d72-a192-e4028e414402>

**Comment by Jai-Prakash-HU** [comment]
I think there is some problem with labs.get_model_calc_dependencies function itself.  It never returns anything and keeps running. Just to test I gave wrong workspace name, and it was still running. 


is it like run_model_bpa is depended on get_model_calc_dependencies in some scenario? and in those scenarios run_model_bpa is running for forever?

![Image](https://github.com/user-attachments/assets/2c7c49a5-a955-43cd-b4bf-80b650600d52)


![Image](https://github.com/user-attachments/assets/949a0862-0af8-4153-b989-c79f4386d7ef)

**Comment by m-kovalsky** [comment]
Yes, run_model_bpa is dependent on get_model_calc_dependencies. Every time you call run_model_bpa, get_model_calc_dependencies is run in the background in order to satisfy specific rules. Can you run this DMV against that model in DAX studio (against the original model)? 

SELECT * FROM $SYSTEM.DISCOVER_CALC_DEPENDENCY

**Comment by Jai-Prakash-HU** [comment]
Update: earlier it was running forever. Now it is throwing error. 

1. SELECT * FROM $SYSTEM.DISCOVER_CALC_DEPENDENCY:  It is working fine. It gives result within seconds
2. labs.get_model_calc_dependencies(dataset = 'XXXXXXXXXXXXXXXXX',  workspace = 'XXXXXXXXXXXXXXXX') : Working fine It gives result within seconds
3. labs.run_model_bpa(dataset = 'XXXXXXXXXXXXXXXXXXXXX',  workspace = 'XXXXXXXXXXXXXXXXXXXX') : It is throwing error. 

please check the error below:

 816             "Naming Conventions",
    817             ["Table", "Column", "Measure", "Partition", "Hierarchy"],
    818             "Warning",
    819             "Object names must not contain special characters",
    820             lambda obj, tom: re.search(r"[\t\r\n]", obj.Name),
    821             "Object names should not include tabs, line breaks, etc.",
    822         ),
    823     ],
    824     columns=[
    825         "Category",
    826         "Scope",
    827         "Severity",
    828         "Rule Name",
    829         "Expression",
    830         "Description",
    831         "URL",
    832     ],
    833 )
    835 return rules

File ~/cluster-env/clonedenv/lib/python3.11/site-packages/sempy_labs/tom/_model.py:2281, in TOMWrapper.is_field_parameter(self, table_name)
   2276 import Microsoft.AnalysisServices.Tabular as TOM
   2278 t = self.model.Tables[table_name]
   2280 return (
-> 2281     self.is_field_parameter(table_name=table_name)
   2282     and t.Columns.Count == 4
   2283     and any(
   2284         "NAMEOF(" in p.Source.Expression.replace(" ", "") for p in t.Partitions
   2285     )
   2286     and all(
   2287         "[Value" in c.SourceColumn
   2288         for c in t.Columns
   2289         if c.Type == TOM.ColumnType.Data
   2290     )
   2291     and any(
   2292         ep.Name == "ParameterMetadata"
   2293         for c in t.Columns
   2294         for ep in c.ExtendedProperties
   2295     )
   2296 )

File ~/cluster-env/clonedenv/lib/python3.11/site-packages/sempy_labs/tom/_model.py:2281, in TOMWrapper.is_field_parameter(self, table_name)
   2276 import Microsoft.AnalysisServices.Tabular as TOM
   2278 t = self.model.Tables[table_name]
   2280 return (
-> 2281     self.is_field_parameter(table_name=table_name)
   2282     and t.Columns.Count == 4
   2283     and any(
   2284         "NAMEOF(" in p.Source.Expression.replace(" ", "") for p in t.Partitions
   2285     )
   2286     and all(
   2287         "[Value" in c.SourceColumn
   2288         for c in t.Columns
   2289         if c.Type == TOM.ColumnType.Data
   2290     )
   2291     and any(
   2292         ep.Name == "ParameterMetadata"
   2293         for c in t.Columns
   2294         for ep in c.ExtendedProperties
   2295     )
   2296 )

    [... skipping similar frames: TOMWrapper.is_field_parameter at line 2281 (2967 times)]

File ~/cluster-env/clonedenv/lib/python3.11/site-packages/sempy_labs/tom/_model.py:2281, in TOMWrapper.is_field_parameter(self, table_name)
   2276 import Microsoft.AnalysisServices.Tabular as TOM
   2278 t = self.model.Tables[table_name]
   2280 return (
-> 2281     self.is_field_parameter(table_name=table_name)
   2282     and t.Columns.Count == 4
   2283     and any(
   2284         "NAMEOF(" in p.Source.Expression.replace(" ", "") for p in t.Partitions
   2285     )
   2286     and all(
   2287         "[Value" in c.SourceColumn
   2288         for c in t.Columns
   2289         if c.Type == TOM.ColumnType.Data
   2290     )
   2291     and any(
   2292         ep.Name == "ParameterMetadata"
   2293         for c in t.Columns
   2294         for ep in c.ExtendedProperties
   2295     )
   2296 )

RecursionError: maximum recursion depth exceeded

**Comment by m-kovalsky** [comment]
Ah, my mistake. I will fix this in a quick release. Thanks for raising the issue.

**Comment by m-kovalsky** [comment]
Fixed in [0.8.6](https://github.com/microsoft/semantic-link-labs/releases/tag/0.8.6).
