### ISSUE TITLE
vertipaq_analyzer fails if vertipaqanalyzer_columns is empty

### ISSUE THREAD

**Issue by Jai-Prakash-HU** [microsoft/semantic-link-labs#275]
vertipaq_analyzer fails if vertipaqanalyzer_columns table is empty

Let's assume I ran vertipaq_analyzer and it created and saved results in default vertipaqanalyzer_columns  then I moved this result to some other table and deleted data from vertipaqanalyzer_columns table and made it empty to collect result next day. Then next day it doesn't work. It throws error.

Current solution is I need to DROP vertipaqanalyzer_columns table and then only I can run vertipaq_analyzer again

So summary is vertipaq_analyzer doesn't work if my vertipaqanalyzer_columns table is empty.

![Image](https://github.com/user-attachments/assets/cd7d9efa-a419-418c-add2-56e5c3b59101)

**Comment by m-kovalsky** [comment]
This will be fixed in the same PR that fixes #266
