### ISSUE TITLE
sempy_labs.report.run_report_bpa  supports only PBIR format ?

### ISSUE THREAD

**Issue by Jai-Prakash-HU** [microsoft/semantic-link-labs#285]
Could you please provide information of below points?

1. sempy_labs.report.run_report_bpa  runs  only on PBIR format report?
2. If yes for above then do we have any alternate solution if we want to scan non-pbir format report?
3. This function will support bulk scan in future.?
4. All the report related functions (sempy_labs.report.XXXXXXXXXXXXX) runs only on PBIR format?
5. Where can I see these limitations on semantic link functions? I mean I couldn't find any document saying functions limitations.

**Comment by m-kovalsky** [comment]
The ReportWrapper necessitates the report be in the PBIR format. I'll make sure the docs says so. Any function which depends on the ReportWrapper has the same requirement. There is no plan to do this for non-PBIR format as PBIR will become the new default in the near future. Not all functions in the report package require the report to be in PBIR format - only the ones which reference ReportWrapper (which I don't think is any).

run_report_bpa_bulk is certainly a possibility for a future function.
