### ISSUE TITLE
Incorrect column and Data order by run_model_bpa export and Discrepancy in Results Between run_model_bpa and run_model_bpa_bulk Functions

### ISSUE THREAD

**Issue by Jai-Prakash-HU** [microsoft/semantic-link-labs#288]
Discrepancy in Data Order and Results Between run_model_bpa and run_model_bpa_bulk Functions
Dear Microsoft Support Team,

I am encountering an issue with the run_model_bpa function not saving data in the correct order in the modelbparesults table. Below are the details of the scenarios I tested:

Initial Scenario:
The table modelbparesults was already present in the lakehouse. Running run_model_bpa did not save the results in the proper order.

Dropping and Recreating the Table:
I dropped the modelbparesults table and re-ran the run_model_bpa function. However, it still did not save the results in the correct order.

Using run_model_bpa_bulk:
When I ran the run_model_bpa_bulk function, it successfully saved the data in the correct order.

Discrepancy in Results Count:
In a simple test dataset, run_model_bpa_bulk returned 8 rows, while run_model_bpa returned only 4 rows.

Request:
For our automation process, we rely on both run_model_bpa and run_model_bpa_bulk functions operating consistently on the same lakehouse table (modelbparesults). Please ensure both functions:

Save data in the same order.
Return consistent and accurate results.
Attached is a screenshot highlighting the issue for reference.

![Image](https://github.com/user-attachments/assets/dd981174-8743-4574-a3ea-b5807e73ff04)

In the below screenshot first 4 rows are by run_model_bpa and last 8 rows by run_model_bpa_bulk

![Image](https://github.com/user-attachments/assets/e1c3fead-bdca-4458-b207-c04c358ccd33)

**Comment by m-kovalsky** [comment]
Made a fix for the next release

**Comment by m-kovalsky** [comment]
Fixed in [0.8.7](https://github.com/microsoft/semantic-link-labs/releases/tag/0.8.7).
