### ISSUE TITLE
Plans for exporting/importing TMDL for semantic models?

### ISSUE THREAD

**Issue by jamescl604** [microsoft/semantic-link-labs#300]
Just curious if there are plans to support the ability to export a semantic model to TMDL as well as support imports from TMDL.   I'd like to crawl all the model definitions as text and use GPT to do certain tasks, like documentation to translations.

**Comment by m-kovalsky** [comment]
Yes. In what format would you prefer the output to be in. With TMSL it's just a single .bim file so it's easy to handle. With TMDL it's a whole bunch of files so the output is more complicated.

**Comment by jamescl604** [comment]
I was looking at this type of syntax which is available from AMO:  https://learn.microsoft.com/en-us/analysis-services/tmdl/tmdl-how-to | https://learn.microsoft.com/en-us/dotnet/api/microsoft.analysisservices.tmdlserializer?view=analysisservices-dotnet

It supports use cases of serializing to a folder, to a text variable, and the reverse which is pretty handy if it was only available from Python : )

**Comment by m-kovalsky** [comment]
Added the get_semantic_model_definition function in [0.8.9](https://github.com/microsoft/semantic-link-labs/releases/tag/0.8.9).
