### ISSUE TITLE
Functions for creating and deleting workspaces

### ISSUE THREAD

**Issue by sp-ics-mf** [microsoft/semantic-link-labs#302]
**Is your feature request related to a problem? Please describe.**
Currently, there are no functions for creating or deleting workspaces.

**Describe the solution you'd like**
A function that calls the respective REST API with at least 1 mandatory parameter (workspace name).
Sources:
[Workspaces - Create Workspace - REST API (Core) | Microsoft Learn](https://learn.microsoft.com/en-gb/rest/api/fabric/core/workspaces/create-workspace?tabs=HTTP)
[Workspaces - Delete Workspace - REST API (Core) | Microsoft Learn](https://learn.microsoft.com/en-gb/rest/api/fabric/core/workspaces/delete-workspace?tabs=HTTP)

**Comment by m-kovalsky** [comment]
Any item can be deleted with this [function](https://learn.microsoft.com/en-us/python/api/semantic-link-sempy/sempy.fabric?view=semantic-link-python#sempy-fabric-delete-item) in semantic link. Semantic link already has a [create_workspace](https://learn.microsoft.com/en-us/python/api/semantic-link-sempy/sempy.fabric?view=semantic-link-python#sempy-fabric-create-workspace) function

```python
import sempy.fabric as fabric
fabric.create_workspace(display_name='myneworkspace', capacity_id=None)
```

```python
import sempy.fabric as fabric

workspace_name = 'myneworkspace'
item_id = fabric.resolve_workspace_id(workspace_name)
fabric.delete_item(item_id=item_id)
```
