### ISSUE TITLE
run_model_bpa_bulk  generating duplicate row for first dataset in the list. And  extended = True has no impact in run_model_bpa

### ISSUE THREAD

**Issue by Jai-Prakash-HU** [microsoft/semantic-link-labs#314]
Let's assume I have 5 datasets in a workspace, if I run  run_model_bpa_bulk  then it creates exactly double rows in the table for first dataset. 
I tested it multiple times. please confirm. 

It can be easily tested by comparing the result of 

**select distinct * from modelbparesults**    VS   **select  * from modelbparesults.**

I have another question. Could you please explain difference between below two scenarios? It gives exactly same result.  But first takes more than double time than 2nd one. If result is same, then what is the point of running the first one in below screenshot. 

![Image](https://github.com/user-attachments/assets/898459c2-f8ea-41d4-a4f1-690b704dd195)

Result can be compared as below. I ran both versions as above and then compared the result as below. It gave nothing. Both are exactly same.  

select distinct [Capacity_Name],
			[Capacity_Id],
			[Workspace_Name],
			[Workspace_Id],
			[Dataset_Name],
			[Dataset_Id],
			[Configured_By],
			[Rule_Name],
			[Category],
			[Severity],
			[Object_Type],
			[Object_Name],
			[Description],
			[URL] from modelbparesults  where RunId = 1
except 

select distinct [Capacity_Name],
			[Capacity_Id],
			[Workspace_Name],
			[Workspace_Id],
			[Dataset_Name],
			[Dataset_Id],
			[Configured_By],
			[Rule_Name],
			[Category],
			[Severity],
			[Object_Type],
			[Object_Name],
			[Description],
			[URL] from modelbparesults  where  RunId = 2

**Comment by m-kovalsky** [comment]
Please raise different issues as different threads. 

If you set extended=True and the result is the same it means your model didn’t violate any of the rules which leverage extended=True (vertipaq stats).

**Comment by m-kovalsky** [comment]
Fixed in [0.8.9](https://github.com/microsoft/semantic-link-labs/releases/tag/0.8.9).
