### ISSUE TITLE
migration.migrate_model_objects_to_semantic_model - Breaks after 'Creating Hierarchies' message

### ISSUE THREAD

**Issue by bharatn008** [microsoft/semantic-link-labs#32]
Breaks after the message 'Creating Hierarchies', didnt get any error or something it just breaks

![image](https://github.com/microsoft/semantic-link-labs/assets/171952045/f84024d0-f6dd-4d9e-ae09-5b49a6d6155c)

As in the snapshot, after 'creating hierarchies' it directly goes to the field parameter functions and skips all the other model objects like relationships

**Comment by m-kovalsky** [comment]
This is odd. Do you have any hierarchies in the original semantic model?

**Comment by bharatn008** [comment]
Yes, refer the snapshot, its from the original semantic model


![image](https://github.com/microsoft/semantic-link-labs/assets/171952045/3fd7cf4d-1a38-4882-aebf-3cfa3071575d)

**Comment by bharatn008** [comment]
As it gets breaks in Hierarchy segment, all the other model objects are also not get migrated. Have tried commenting out the Hierarchy part and then all model objects got migrated like measure, relationships, etc.

**Comment by bharatn008** [comment]
Have tried with latest install but its the same. Stops after the 'hierarchies' message

![image](https://github.com/user-attachments/assets/0ef422e4-ec01-469e-ba73-1c3927253c55)

**Comment by m-kovalsky** [comment]
This should be resolved in [0.7.0](https://github.com/microsoft/semantic-link-labs/releases/tag/0.7.0).
