### ISSUE TITLE
Translate a semantic model's metadata bug

### ISSUE THREAD

**Issue by shurikool** [microsoft/semantic-link-labs#326]
Hello,

I encountered some issues in translation with three cases.
When the name of the column is "description", it will not translate it, maybe because it's a name of a property ?
If I have the same of column, for example "Color" but in two different tables, the two columns will not be translated.
Display folders are never translated

Thank you for your big effort

**Comment by m-kovalsky** [comment]
Thank you for raising the issue. I've made a PR for this fix for the next release.

**Comment by m-kovalsky** [comment]
Fixed in [0.8.9](https://github.com/microsoft/semantic-link-labs/releases/tag/0.8.9).
