### ISSUE TITLE
Dependencies not installed when using a custom Fabric Environment

### ISSUE THREAD

**Issue by thedaxshepherd** [microsoft/semantic-link-labs#327]
**What are you trying to achieve?**
Would like to know if using a custom Fabric Environment (https://github.com/microsoft/semantic-link-labs#load-semantic-link-labs-into-a-custom-fabric-environment) to install Semantic-Link-Labs should be installing the dependencies listed in the environment.yml. 

Is this a limitation of using custom Fabric Environments at this time or if this is expected behavior? I could not find anything in the documentation on Environments or any open issues.

My main concern is that I am going to run into issues running certain code if the dependencies are outdated.  

**What have you tried so far?**

If I use the custom Fabric Environment to install Semantic Link Labs, it does not install the dependencies listed in the environment.yml, such as Semantic-Link-Sempy version 0.8.3.

But if I install it from the notebook using %pip install semantic-link-labs then it installs the necessary dependencies.

I am verifying what version is installed with %pip freeze.

Also, If I try to view the dependencies in the Environment under Public Libraries- it does not show any dependencies.

**Comment by m-kovalsky** [comment]
Thanks for raising the issue. It is being investigated.

**Comment by whiskyboy** [comment]
@thedaxshepherd can you try running "import sempy; print(sempy.__version__)" in your environment? It should print the right version (0.8.3 at this moment)

As long as sempy.__version__ is printing the correct version there shouldn’t be any issue when running certain code. The runtime will pick the version printed by __version__ method. But let us know if you encounter any issue.

**Comment by m-kovalsky** [comment]
@whiskyboy @thedaxshepherd I tried that and it shows 0.8.3 when using an environment which contains semantic-link-labs. It seems the dependencies are installed properly but not showing in the package code run by @thedaxshepherd.

**Comment by thedaxshepherd** [comment]
Yes, it prints 0.8.3 using an environment containing Semantic-Link-Labs. I assume this is due to how Environments are implemented. I stumbled across trying to show how to check what version is currently installed as part of a more extended presentation. I would appreciate any guidance on how to check the version or background on why this is the case. I am still learning Python and using it in the Fabric Notebooks. 

Otherwise, I will make sure to note how to check the version when using it with an Environment.

**Comment by m-kovalsky** [comment]
I generally used the code in my Fabric repository (under m-kovalsky) but that yielded the old package version. Anyways, this isn’t an issue with semantic link labs so closing it out here. Seems like an issue for the environment team to fix.
