### ISSUE TITLE
Post Migration To direct Lake semantic model Edit tables is not opening!

### ISSUE THREAD

**Issue by cvlmonica** [microsoft/semantic-link-labs#34]
We have a import mode semantic model which has source synapse dedicated sql pool and have various objects such as calculated tables, calculated columns ,measures, roles etc. 
All the tables have been moved to lakehouse and calculated tables and columns has been taken care in ETL logic.
While we ran the migration script, among 2 calculated tables one table has shown up in the direct lake semantic model while other didn't! so we thought of adding it through edit tables feature but it is not working!

![image](https://github.com/user-attachments/assets/1a9fc563-2286-45b5-8fe3-060a1d9dfd9b)

We connected to the tabular editor to check if any error exists. But we don't see any errors!

Any other ways to add that calculated table into the direct lake semantic model!? If so please do let me know!

**Comment by m-kovalsky** [comment]
Was the calculated table which was added a field parameter? If so, this is a known issue - that the edit tables function stops working properly if you have a calculated table in a direct lake model.

As a workaround, I will be releasing a new function which allows you to add easily new tables to a direct lake model  based on a lakehouse table.
________________________________
From: cvlmonica ***@***.***>
Sent: Monday, July 15, 2024 10:16:48 AM
To: microsoft/semantic-link-labs ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/semantic-link-labs] Post Migration To direct Lake semantic model Edit tables is not opening! (Issue #34)


We have a import mode semantic model which has source synapse dedicated sql pool and have various objects such as calculated tables, calculated columns ,measures, roles etc.
All the tables have been moved to lakehouse and calculated tables and columns has been taken care in ETL logic.
While we ran the migration script, among 2 calculated tables one table has shown up in the direct lake semantic model while other didn't! so we thought of adding it through edit tables feature but it is not working!

image.png (view on web)<https://github.com/user-attachments/assets/1a9fc563-2286-45b5-8fe3-060a1d9dfd9b>

We connected to the tabular editor to check if any error exists. But we don't see any errors!

Any other ways to add that calculated table into the direct lake semantic model!? If so please do let me know!

**Comment by m-kovalsky** [comment]
Calculated columns will not show as migrated because they are not migrated as part of this solution.

Calculated tables are migrated but because their ‘type’ changes from ‘calculated table’ to ‘table’ it may appear that they are not migrated.

Regarding the main issue here - it is not an issue with semantic link labs - it is an issue with the power bi service.
