### ISSUE TITLE
ValueError: numpy.dtype size changed

### ISSUE THREAD

**Issue by suketududhat** [microsoft/semantic-link-labs#343]
**Describe the bug**
```
import sempy
import sempy-labs
```

Notebook imports are both giving the same error (`%pip install semantic-link-labs` also gives same error):
`ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject`

**To Reproduce**
1. Connect to default workspace environment in a notebook
2. Run notebook with either import or install functions

**Expected behavior**
It has never caused this error until yesterday

**Screenshots**
![Image](https://github.com/user-attachments/assets/d4d8ad3b-af9f-4312-ae82-134571f54ec7)

**Desktop (please complete the following information):**
 - Windows 11
 - Microsoft Edge
 - Version 131.0.2903.86

**Additional context**

**Comment by m-kovalsky** [comment]
Numpy, datetime, semantic-link are preinstalled in the fabric runtime anyways. No need to have these in the environment.

**Comment by suketududhat** [comment]
Removing those 3 fixed the issue, thank you!
