### ISSUE TITLE
Move a direct lake semantic model to a different workspace

### ISSUE THREAD

**Issue by SheilaHart** [microsoft/semantic-link-labs#349]
We have 10 direct lake semantic models in a premium capacity workspace, P1, in the South Central US region. 
We need to move these models to a Fabric capacity workspace in the East US region.

Is it possible to use Semantic Link to copy or move the direct lake models to a different workspace?

**Comment by SheilaHart** [comment]
We were able to use a deployment pipeline to deploy the model in premium capacity to a workspace in fabric capacity.

**Comment by m-kovalsky** [comment]
You can use [this](https://semantic-link-labs.readthedocs.io/en/stable/sempy_labs.html#sempy_labs.deploy_semantic_model) function. There is actually a bug in the function at the moment but I will be releasing a new version this week which has the fix.
