### ISSUE TITLE
sempy.fabric module missing in sempy_labs?

### ISSUE THREAD

**Issue by dtiles** [microsoft/semantic-link-labs#35]
**Is your feature request related to a problem? Please describe.**
I was using the sempy library, and I was using the PowerBIRestClient which is very powerful, and was inside the sempy fabric module. I'm trying to switch to the new library, but I'm not finding it.
Please forgive me if I'm doing something wrong, but it's the first time I'm opening an Issue on GitHub

**Describe the solution you'd like**
To have again the fabric module inside the sempy_labs library

**Describe alternatives you've considered**
To continue to use sempy library at the moment, but I guess it'll get deprecated

**Comment by m-kovalsky** [comment]
Semantic link labs does not replace semantic link, it augments it. To wield the most power, both libraries should be used in conjunction. Semantic link has the FabricRestClient and PowerBIRestClient methods while semantic link labs has many wrapper functions for power bi and fabric APIs which means you don’t need to worry about calling the API - you just run the function and the API is called in the background.
________________________________
From: dtiles ***@***.***>
Sent: Wednesday, July 17, 2024 6:57:28 PM
To: microsoft/semantic-link-labs ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/semantic-link-labs] sempy.fabric module missing in sempy_labs? (Issue #35)


Is your feature request related to a problem? Please describe.
I was using the sempy library, and I was using the PowerBIRestClient which is very powerful, and was inside the sempy fabric module. I'm trying to switch to the new library, but I'm not finding it.
Please forgive me if I'm doing something wrong, but it's the first time I'm opening an Issue on GitHub

Describe the solution you'd like
To have again the fabric module inside the sempy_labs library

Describe alternatives you've considered
To continue to use sempy library at the moment, but I guess it'll get deprecated
