### ISSUE TITLE
labs.run_model_bpa_bulk() doesn't work with schema enabled workspace

### ISSUE THREAD

**Issue by TimDataEng** [microsoft/semantic-link-labs#352]
**Describe the bug**

labs.run_model_bpa_bulk() doesn't work with schema enabled workspace.

**To Reproduce**

1. in notebook, run "labs.run_model_bpa_bulk(workspace=['workspacename'])"
2. See error

**Expected behavior**

FabricHTTPException: 400 Bad Request for url: https://api.fabric.microsoft.com//v1/workspaces/8c36a728-4e69-40fa-b241-831064386b99/lakehouses/8167a262-c245-43c9-ae09-7b267183f4df/tables
Error: {"requestId":"e8c840f0-783d-4538-a591-5560e55fbfdf","errorCode":"UnsupportedOperationForSchemasEnabledLakehouse","message":"The operation is not supported for Lakehouse with schemas enabled."}
Headers: {'Content-Length': '192', 'Content-Type': 'application/json; charset=utf-8', 'x-ms-public-api-error-code': 'UnsupportedOperationForSchemasEnabledLakehouse', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'X-Frame-Options': 'deny', 'X-Content-Type-Options': 'nosniff', 'Access-Control-Expose-Headers': 'RequestId', 'request-redirected': 'true', 'home-cluster-uri': 'https://wabi-us-east2-b-primary-redirect.analysis.windows.net/', 'RequestId': 'e8c840f0-783d-4538-a591-5560e55fbfdf', 'Date': 'Sun, 15 Dec 2024 00:48:29 GMT'}

**Comment by m-kovalsky** [comment]
See #173. This is not related to semantic link labs. APIs are not currently supported for schema-enabled lakehouses.

**Comment by TimDataEng** [comment]
Yea, it is in public review now. Thanks a lot Michael!
