### ISSUE TITLE
Increase Timeout Value for Semantic Link Labs Cache Warming Feature

### ISSUE THREAD

**Issue by Oddjobe** [microsoft/semantic-link-labs#359]
**What are you trying to achieve?**
The current timeout value for this function is insufficient for our data processing needs. 
As a result, the cache warming process frequently times out.

**What have you tried so far?**
directlake.warm_direct_lake_cache_perspective(dataset=dataset_name, workspace=workspace_name, perspective='', add_dependencies=True)

Error:
Caused by AdomdErrorResponseException: 
The XML for Analysis request timed out before it was completed. Timeout value: 1200 sec.

Ask:
Can this feature be added as a feature or can it already set in some way.

**Comment by m-kovalsky** [comment]
Not related to notebook.
