### ISSUE TITLE
Feature Request - VisualID search

### ISSUE THREAD

**Issue by rosscouldrey** [microsoft/semantic-link-labs#362]
**Is your feature request related to a problem? Please describe.**
From the workspace monitoring (or the log analytics) i can find the Visual ID for a visual that contributes to my capacity utilization (for optimization purposes).  But currently with a VisualID it can be difficult to identify where in the report this resides (specifically for large reports with multiple pages and lots of visuals).

**Describe the solution you'd like**
Would be great to have a function in semantic link labs that allows me to pass a visualID and return details of the visual - either name, or page, or type, or location on page, etc.

**Describe alternatives you've considered**
I've tried using PBIP format - but since moving to TMDL, the report.json no longer contains a complete list of visuals.  Its now split by page, and requires a lot of tedious searching.

I've also tried using the embedded APIs - but this requires you to loop through pages, and print all visuals per page, and then search.  Its also quite a few clicks.

**Additional context**

**Comment by m-kovalsky** [comment]
The list_visuals function within the ReportWrapper gives you this info for all visuals within a report.

Here is a notebook which shows how to use it and other related functions.

https://github.com/microsoft/semantic-link-labs/blob/main/notebooks/Report%20Analysis.ipynb
