### ISSUE TITLE
vertipaq_analyzer and run_model_bpa  capacityname empty and datasetid error

### ISSUE THREAD

**Issue by shurikool** [microsoft/semantic-link-labs#363]
Hello

While using vertipaq_analyzer and run_model_bpa :
1-the capacityname column in the lakehouse is always empty
2-While putting datasetid in the dataset parameter instead of the dataset name, I encounter an error => AmoException: The 'Database' with 'Name' = '438ffbd5-6bf0-48c7-9fab-a3b5e101df56' doesn't exist in the collection.
   at Microsoft.AnalysisServices.NamedComponentCollection.BaseGetByName(String name, Boolean throwIfNotFound)
   at Microsoft.AnalysisServices.Tabular.DatabaseCollection.GetByName(String name)

Thank you for your help

**Comment by m-kovalsky** [comment]
Which version are you using? Make sure you are running the latest (0.8.10).

**Comment by m-kovalsky** [comment]
Also, vertipaq_analyzer currently only supports the semantic model name, not the ID.

**Comment by shurikool** [comment]
Hello back,

I changed to 0.8.10 (I was on the 0.8.9)
The semantic model id works fine now for the run_model_bpa. You are right it does not work for vertipaq_analyzer.
However, the capacity_name column is always null in the delta tables

**Comment by m-kovalsky** [comment]
This should be resolved in [0.8.11](https://github.com/microsoft/semantic-link-labs/releases/tag/0.8.11) - as long as you have the proper permissions to view the capacity info.
