### ISSUE TITLE
Error while using update_direct_lake_partition_entity() Function!

### ISSUE THREAD

**Issue by cvlmonica** [microsoft/semantic-link-labs#37]
In import mode I had spaces in the table names and as lakehouse we have removed them to map it we can use this function update_direct_lake_partition_entity()! so I tried but got the below error!

![image](https://github.com/user-attachments/assets/cc6014a4-3492-4795-af4d-b04c83a01c80)

I have also tried changing the partition names manually in tabular editor but still while I am doing the refresh it says the below error:
![image](https://github.com/user-attachments/assets/b995a7b5-c36a-41d6-a5f4-6bff1fe8e683)

Any alternative way to map the lakehouse tables to semantic model!?

**Comment by m-kovalsky** [comment]
It looks like there is a data type issue with one of the columns in one of your tables. Check the data types between the columns in the delta table in the lakehouse and the columns in the table in the semantic model.

**Comment by m-kovalsky** [comment]
Are you still experiencing this issue with the latest version?
