### ISSUE TITLE
sempy-labs connect_workspace_to_git() function contradictory errors from function and API

### ISSUE THREAD

**Issue by UJCG** [microsoft/semantic-link-labs#370]
Bug: 

When using the sempy-labs connect_workspace_to_git() function, it gives me an error message.

I used the following code with the parameters as mentioned:
`labs.connect_workspace_to_git(organization_name="<orgname>", repository_name="<reponame>", branch_name="<branchname>", project_name="<reponame>", directory_name="<foldername>", git_provider_type="GitHub", workspace="<workspacename>")`

ErrorMessage:
FabricHTTPException: 400 Bad Request for url..."moreDetails":[{"errorCode":"InvalidParameter","message":"The OwnerName field is required."}],"message":"The request has an invalid input"}

When I referred to the API code, I can see it requires OwnerName (here is the example [from the documentation](https://learn.microsoft.com/en-us/rest/api/fabric/core/git/connect?tabs=HTTP#connect-a-workspace-to-github-example))
POST https://api.fabric.microsoft.com/v1/workspaces/1565e6a3-c020-4c0c-dda7-92bafe99eec5/git/connect

{
  "gitProviderDetails": {
    "ownerName": "Test Owner",
    "gitProviderType": "GitHub",
    "repositoryName": "Test Repo",
    "branchName": "Test Branch",
    "directoryName": "Test Directory/Test Subdirectory"
  },
  "myGitCredentials": {
    "source": "ConfiguredConnection",
    "connectionId": "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
  }
}

We can see there is a difference in the arguments needed by the function and the API such as OwnerName and ProjectName etc..,

So when I call the code with the ownerName (or OwnerName) as follows:

`labs.connect_workspace_to_git(organization_name="<orgname>", repository_name="<reponame>", branch_name="<branchname>", project_name="<reponame>", ownerName="<ownername>", directory_name="<foldername>", git_provider_type="GitHub", workspace="<workspacename>")`

it then gives me the error:

TypeError: connect_workspace_to_git() got an unexpected keyword argument 'ownerName'

Docs referred to apart from this git repo:
[sempy-labs library docs ](https://semantic-link-labs.readthedocs.io/en/stable/sempy_labs.html#sempy_labs.connect_workspace_to_git)
[API documentation](https://learn.microsoft.com/en-us/rest/api/fabric/core/git/connect?tabs=HTTP#connect-a-workspace-to-github-example)

Has anyone seen and resolved this issue? Thanks!

**Comment by m-kovalsky** [comment]
Thanks for raising this issue. It appears this API has been updated to support not just Azure DevOps but GitHub too. Since the API request bodies are different enough they probably warrant their own functions (connect_workspace_to_github & connect_workspace_to_azure_dev_ops).

**Comment by m-kovalsky** [comment]
The new functions are available in [0.8.11](https://github.com/microsoft/semantic-link-labs/releases/tag/0.8.11).
