### ISSUE TITLE
I was not able to find a CreateLakehouse function. Can we expect to get one?

### ISSUE THREAD

**Issue by jdkorigan** [microsoft/semantic-link-labs#376]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by m-kovalsky** [comment]
This is already available in semantic link

https://learn.microsoft.com/en-us/python/api/semantic-link-sempy/sempy.fabric?view=semantic-link-python#sempy-fabric-create-lakehouse
