### ISSUE TITLE
The list_item_job_instances() fails when trying to return Job history for dataflows

### ISSUE THREAD

**Issue by clausm73** [microsoft/semantic-link-labs#377]
I have tried to use the function list_item_job_instances() to display job history for dataflows in my workspace, but I'm told the item doesn't exist - which is incorrect.

![Image](https://github.com/user-attachments/assets/f7d09b63-2d0c-4875-b19c-396bed13ca77)

**Comment by m-kovalsky** [comment]
Currently, dataflows (gen1 or gen2) are not supported item types in the Fabric APIs.

https://learn.microsoft.com/en-us/rest/api/fabric/core/items/list-items?tabs=HTTP#itemtype
