### ISSUE TITLE
Documentation: Highlight the use-case when converting from AAS (models that have no PowerQuery)

### ISSUE THREAD

**Issue by gefawcet** [microsoft/semantic-link-labs#39]
This is just a request to add some highlighting/emphasis to part of the documentation.

The information is already there (it says, ignore steps 1-4 if your model doesn't have PowerQuery).

But I walked through this with a customer today who is brining over models from AAS, and it just seemed like it would just add clarity if there was a bold/larger-font callout of "If you are converting models from AAS ...", or something to that effect.

**Comment by m-kovalsky** [comment]
Being in AAS has nothing to do with Power Query. A semantic model in AAS may or may not use Power Query. I can update the documentation but I wouldn't put anything specific about AAS as it is not relevant for the discussion about Power Query.

**Comment by gefawcet** [comment]
OK.

GEOFF FAWCETT
Principal Technology Specialist - Business Intelligence
425-233-9843
***@***.***
