### ISSUE TITLE
Update From and To Git

### ISSUE THREAD

**Issue by muhssamy** [microsoft/semantic-link-labs#48]
can we use semantic-link-labs for operations like update workspace from git Repo ?
https://learn.microsoft.com/en-us/rest/api/fabric/core/git/update-from-git?

**Comment by m-kovalsky** [comment]
As of now there are no functions for these operations. You could use semantic link’s FabricRestClient to do this but it would involve some coding. I plan to add wrapper functions in semantic link labs for the remaining Fabric and Power BI APIs including these.
________________________________
From: muhssamy ***@***.***>
Sent: Sunday, July 28, 2024 3:35:52 PM
To: microsoft/semantic-link-labs ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/semantic-link-labs] Update From and To Git (Issue #48)


can we use semantic-link-labs for operations like update workspace from git Repo ?
https://learn.microsoft.com/en-us/rest/api/fabric/core/git/update-from-git?

**Comment by m-kovalsky** [comment]
please keep issues open until they are resolved. thanks!

**Comment by blaine12100** [comment]
@m-kovalsky I know that semantic-link-labs is meant to be used in a notebook but could it also be used as part of an automation process? I've tried a bit on this but I do not know how can I pass an access token to the internal API calls done by this package.

**Comment by m-kovalsky** [comment]
Semantic link and semantic link labs can only be run from a Fabric notebook. You can schedule notebooks and also run pipelines in notebooks for automation scenarios.
________________________________

**Comment by m-kovalsky** [comment]
Wrapper functions for the Git APIs are in [0.7.3](https://github.com/microsoft/semantic-link-labs/releases/tag/0.7.3).
