### ISSUE TITLE
Vacuum tables in Lakehouse

### ISSUE THREAD

**Issue by GilbertQue** [microsoft/semantic-link-labs#50]
Hi there,

Would it be possible to create an option to Vacuum tables in the Lakehouse as you have already created it to Optimize the Lakehouse Tables?

Here is the reference: [https://semantic-link-labs.readthedocs.io/en/stable/sempy_labs.lakehouse.html#sempy_labs.lakehouse.optimize_lakehouse_tables](url)

This will allow for automation in the notebook to both Optimize and Vacuum the Lakehouse tables to ensure that they have the right file sizes and then to also not have an data that is no longer required?

**Comment by m-kovalsky** [comment]
Yes, I'd like to add this as well. I will look into it.

**Comment by m-kovalsky** [comment]
This will be coming soon https://github.com/microsoft/semantic-link-labs/pull/69

**Comment by m-kovalsky** [comment]
This is now available in [0.7.1](https://github.com/microsoft/semantic-link-labs/releases/tag/0.7.1).
