### ISSUE TITLE
run_model_BPA fils when export=True is specified

### ISSUE THREAD

**Issue by pawarbi** [microsoft/semantic-link-labs#54]
**Describe the bug**
I have notebook in `workspace A` with a lakehouse attached from the same workspace. I am running BPA on a dataset that is in `workspace B`. `labs.run_model_bpa(dataset=model_name, workspace=ws )` works fine. However, when I attach set `export=True`, it fails with an error : `ValueError: There's no item with the ID '8502a5af-1199-xxxx-4445d517f193' in workspace 'Workspace A'`

I think the issue here is that the code expects the lakehouse to be in the same workspace as the semantic model. Either the docstring should clarify that or the table should be saved to the lakehouse attached to the notebook, irrespective of the workspace of the dataset.
![image](https://github.com/user-attachments/assets/6d0ba7ac-cf67-44cc-a9e6-620fdf76a10c)

- fabric runtime 1.2
- SLL v 0.6.0

**Comment by m-kovalsky** [comment]
Resolved in [0.7.0](https://github.com/microsoft/semantic-link-labs/releases/tag/0.7.0).
