### ISSUE TITLE
Creating a custom semantic model with lakehouse information

### ISSUE THREAD

**Issue by blaine12100** [microsoft/semantic-link-labs#55]
**What are you trying to achieve?**
What I am trying to do is to create a blank semantic model, connect it to a lakehouse in the workspace, define the tables and the columns that I need from the Lakehouse and to add them to my semantic model.

**What have you tried so far?**
I am able to create a custom semantic model using the create_blank_semantic_model function along with the add_table and add_column functions. The issue that I'm facing is I want to connect this semantic model to a lakehouse in the workspace where I'm creating this semantic model in.

Possible solution:

1. Create blank semantic model.
2. Use directlake subpackage to import all tables and columns from the lakehouse
3. Hide / delete objects from the semantic model as required.

I would like to avoid the above approach as it's duplicate work (Add all columns and then remove the ones that you don't need)

@m-kovalsky I believe you might have had a discussion about this with my manager Mr Dave cleaves as well.

**Comment by m-kovalsky** [comment]
Try using the [generate_direct_lake_semantic_model](https://semantic-link-labs.readthedocs.io/en/stable/sempy_labs.directlake.html#sempy_labs.directlake.generate_direct_lake_semantic_model) function in [0.7.0](https://github.com/microsoft/semantic-link-labs/releases/tag/0.7.0).
