### ISSUE TITLE
Add tables to (custom) semantic model

### ISSUE THREAD

**Issue by paulienleeuwenburgh** [microsoft/semantic-link-labs#59]
**What are you trying to achieve?**
I deployed an empty (custom) semantic model (csm) using sempy_labs.deploy_semantic_model(). It's based on the existing (default) semantic model of a lakehouse. As a next step I want to add a selection of the lakehouse's tables to the newly created custom semantic model.

**What have you tried so far?**
I tried running sempy_labs.directlake.add_table_to_direct_lake_semantic_model(), that fails because the empty csm does not identify as a Direct Lake semantic model... yet. As an alternative I tried to start with deploying a blank semantic model using sempy_labs.create_blank_semantic_model(), but that has the same outcome. How could I overcome or workaround this?

**Comment by m-kovalsky** [comment]
I actually encountered the same issue myself the other day. I modified a few functions to enable this to work. The next release of semantic link labs will resolve this issue so stay tuned!

**Comment by m-kovalsky** [comment]
Try the 'add_table_to_direct_lake_semantic_model'. Or, try the new [generate_direct_lake_semantic_model](https://semantic-link-labs.readthedocs.io/en/stable/sempy_labs.directlake.html#sempy_labs.directlake.generate_direct_lake_semantic_model) in [0.7.0](https://github.com/microsoft/semantic-link-labs/releases/tag/0.7.0).
