### ISSUE TITLE
Include custom field names when adding field parameters

### ISSUE THREAD

**Issue by Benjiman89** [microsoft/semantic-link-labs#60]
**Is your feature request related to a problem? Please describe.**
Feature request.  When adding field parameters we then subsequently need to go and change the name in the front end.  No option with [https://semantic-link-labs.readthedocs.io/en/stable/sempy_labs.tom.html#sempy_labs.tom.TOMWrapper.add_field_parameter](url)

**Describe the solution you'd like**
Instead of a list of column names/strings, please could we allow for tuples.
Example:
("id_level1", NAMEOF('dim_customer'[id_level1]), 1)
has to be manually altered to...
("Customer Level 1", NAMEOF('dim_customer'[id_level1]), 1)

It would be easier to be able to do this with code by accepting tuples:
add_field_parameter(table_name: str, objects: List[tuple(str,str)])

**Describe alternatives you've considered**
Only alternative is via front end in web

**Comment by Benjiman89** [comment]
Thanks @m-kovalsky - this is now resolved!:
![image](https://github.com/user-attachments/assets/69f6075d-1e34-47f7-8c2c-7a86d0ec6b20)

**Comment by m-kovalsky** [comment]
Please only mark issues as closed once the changes reflect in a new release. This is coming in the next version to be released shortly.

**Comment by Benjiman89** [comment]
Clear thanks

**Comment by m-kovalsky** [comment]
This is available in [0.7.0](https://github.com/microsoft/semantic-link-labs/releases/tag/0.7.0).
