### ISSUE TITLE
add_table_to_direct_lake_semantic_model() is not working!

### ISSUE THREAD

**Issue by cvlmonica** [microsoft/semantic-link-labs#76]
I have been using this add_table_to_direct_lake_semantic_model() to add my lakehouse table easily. 

But it throws following error:
![image](https://github.com/user-attachments/assets/e0843673-6da7-4d5d-a0ea-88f1506e737a)
![image](https://github.com/user-attachments/assets/7134ae57-6979-40e6-b2d7-5aedfc527598)

what is the issue here?!

Any quick help would be really helpful!

**Comment by m-kovalsky** [comment]
This is due to the lakehouse used by the semantic model being in a different workspace than the semantic model itself. I'm making some updates which will alleviate this situation for the next release.

**Comment by cvlmonica** [comment]
Actually both lakehouse and semantic model is present in the same workspace! But still I am getting this error!

**Comment by m-kovalsky** [comment]
Please try [0.7.0](https://github.com/microsoft/semantic-link-labs/releases/tag/0.7.0).

**Comment by m-kovalsky** [comment]
Please let me know if you are still encountering an issue. If not I will close this issue.
