### ISSUE TITLE
add_table_to_direct_lake_semantic_model not working for Lakehouse tables with shortcuts

### ISSUE THREAD

**Issue by Benjiman89** [microsoft/semantic-link-labs#80]
**Describe the bug**
When using "sempy_labs.directlake.add_table_to_direct_lake_semantic_model" it errors when the lakehouse table is a shortcut.  
We tested for tables that were not shortcuts and there is no issue.
Note everything is within the same workspace.

**To Reproduce**
Run sempy_labs.directlake.add_table_to_direct_lake_semantic_model on a lakehouse table that is a shortcut.

**Expected behavior**
No error.

**Screenshots**
![image](https://github.com/user-attachments/assets/e00b7a79-608e-4cd2-b9b3-06e8d497b1dd)

**Additional context**
I know in other bugs for this function you mention an update coming shortly - does this also fix the above issue?  If so, is there a date?

**Comment by m-kovalsky** [comment]
Thanks for reporting. Made the PR for this and will enable this for all API wrapper functions which support pagination.

**Comment by m-kovalsky** [comment]
This is resolved in [0.7.0](https://github.com/microsoft/semantic-link-labs/releases/tag/0.7.0).
