### ISSUE TITLE
Report Functions not supporting Long Running Operations of Fabric APIs

### ISSUE THREAD

**Issue by Benjiman89** [microsoft/semantic-link-labs#81]
**Describe the bug**
[sempy_labs.report.get_report_json](https://semantic-link-labs.readthedocs.io/en/stable/sempy_labs.report.html#sempy_labs.report.get_report_json) uses the API [Items - Get Report Defintion](https://learn.microsoft.com/en-us/rest/api/fabric/report/items/get-report-definition?tabs=HTTP) but doesn't account for [202 response code of long running operations](https://learn.microsoft.com/en-us/rest/api/fabric/articles/long-running-operation)

**To Reproduce**
1. Run sempy_labs.report.get_report_json in Fabric notebook
2. Receive error: TypeError: 'NoneType' object is not subscriptable
3. Run API call to f'https://api.fabric.microsoft.com/v1/workspaces/{workspaceId}/reports/{reportId}/getDefinition'
4. Response code = 202 and is not accounted for in semantic link labs function, causing the error

**Expected behavior**
sempy_labs.report.get_report_json to run without error

**Screenshots**
![image](https://github.com/user-attachments/assets/a55e10c5-2461-4693-be4e-54a2299a85db)

**Comment by Benjiman89** [comment]
Something along the lines of below could be incorporated (tested works):
![image](https://github.com/user-attachments/assets/067a7cb6-b991-4973-b626-0557d84335c1)

**Comment by Benjiman89** [comment]
Ah - it's only missed in the above function - in another you've included the code:
![image](https://github.com/user-attachments/assets/af70d63d-1363-43af-8092-dc5d07c2e5b8)

So only needs resolving in the "get_report_json" function

**Comment by m-kovalsky** [comment]
Thanks. Made a PR for this. It will go into 0.7.0 coming soon.

**Comment by m-kovalsky** [comment]
This is resolved in [0.7.0](https://github.com/microsoft/semantic-link-labs/releases/tag/0.7.0).
