### ISSUE TITLE
remove_object function doesn't work for tables (missing 2 lines of code)

### ISSUE THREAD

**Issue by Benjiman89** [microsoft/semantic-link-labs#83]
**Describe the bug**
[remove_object](https://semantic-link-labs.readthedocs.io/en/stable/sempy_labs.tom.html#sempy_labs.tom.TOMWrapper.remove_object) doesn't work if object is a table

**To Reproduce**
1. Run tom.remove_object and set object to be a table
2. Runs but table not removed

**Expected behavior**
Table to be removed.

**Screenshots**
Need to include object.Parent.Tables.Remove(object.Name) section here.
![image](https://github.com/user-attachments/assets/79919186-802e-4351-bf76-a2d71d5a455a)

**Additional context**
Fix: Need to include object.Parent.Tables.Remove(object.Name) section here. Currently missing.

**Comment by m-kovalsky** [comment]
Thanks for reporting.

**Comment by m-kovalsky** [comment]
This is resolved in [0.7.0](https://github.com/microsoft/semantic-link-labs/releases/tag/0.7.0).
