### ISSUE TITLE
can't find refresh_semantic_model documentations

### ISSUE THREAD

**Issue by muhssamy** [microsoft/semantic-link-labs#95]
Dears
i am not able to see the documentation of this method refresh_semantic_model()

**Comment by m-kovalsky** [comment]
Thanks. I'm working to resolve this. For now you can use this. The same pattern applies for any function.

```python
import sempy_labs as labs
labs.refresh_semantic_model?
```

**Comment by gbrueckl** [comment]
I think thats the same issue but some (most?) links on the [release page](https://github.com/microsoft/semantic-link-labs/releases/tag/0.7.0) for individual functions - e.g. [refresh_semantic_model](https://semantic-link-labs.readthedocs.io/en/stable/sempy_labs.html#sempy_labs.refresh_semantic_model) do not work

in general, I could not find any documentation on readthedocs.io for that function

**Comment by m-kovalsky** [comment]
I fixed it. There was an issue with the auto-documentation with the stable release. The links now point to the 'latest' release which is working properly. For versions after 0.7.0 it will be best to use the stable version of the docs.
